---
layout: post
title: Unchecked Checked Exceptions in Java
date: '2014-02-09T22:55:00.000+01:00'
author: martin
tags:
- java
modified_time: '2014-02-09T22:55:01.890+01:00'
blogger_id: tag:blogger.com,1999:blog-987786588703208935.post-8253193513810901871
blogger_orig_url: http://bxm-dev.blogspot.com/2014/02/unchecked-checked-exceptions-in-java.html
category: dev
---

In the past, I didn't have much thoughts about checked exceptions. I kind of grew up with them, and I had no hard feelings about them (as long as API designers used them with caution). So an article in the most recent <a href="https://jaxenter.de/magazines/Java-Magazin-314-170797">Java Magazin</a> by <a href="http://haase-consulting.com/">Arno Haase</a> took me by surprise, how easy checked exceptions can be bypassed:<br /><br /><blockquote class="tr_bq"><span style="font-size: x-small;"><span style="font-family: &quot;Courier New&quot;,Courier,monospace;">public class Unchecker {<br /><br />&nbsp;&nbsp;&nbsp; public static void main(String[] args) {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throwUnchecked(new java.io.IOException());<br />&nbsp;&nbsp;&nbsp; }<br /><br />&nbsp;&nbsp;&nbsp; private static void throwUnchecked(Exception exception) {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Unchecker.&lt;RuntimeException&gt;throwIt(exception);<br />&nbsp;&nbsp;&nbsp; }<br /><br />&nbsp;&nbsp;&nbsp; private static &lt;E extends Exception&gt; void throwIt(Exception e) throws E {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw (E)e;<br />&nbsp;&nbsp;&nbsp; }<br />}</span></span></blockquote><br />In the code above, the main method doesn't declare an checked IOExcecption, but it throws it nevertheless:<br /><blockquote class="tr_bq"><span style="font-size: x-small;"><span style="font-family: &quot;Courier New&quot;,Courier,monospace;">$ java Unchecker<br />Exception in thread "main" java.io.IOException<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Unchecker.main(Unchecker.java:4)</span></span></blockquote>And as a funny sidenote: the compiler prevents you from handling this exception with a regular "catch" clause...<br />Type erasure FTW ;)